apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: number-search
spec:
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:7.17.0
        args:
        - -e
        - -c
        - /etc/apm-server/apm-server.yml
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8200
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/apm-server/apm-server.yml
          subPath: apm-server.yml
      volumes:
      - name: config
        configMap:
          name: elastic-config
          items:
            - key: apm-server.yml
              path: apm-server.yml