apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: number-search
data:
  elasticsearch.yml: |
    cluster.name: docker-cluster
    discovery.type: single-node
    xpack.security.enabled: false
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
    setup.kibana:
      host: "kibana:5601"
    setup.template.enabled: true