apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-search-app
  namespace: number-search
spec:
  selector:
    matchLabels:
      app: number-search-app
  template:
    metadata:
      labels:
        app: number-search-app
    spec:
      containers:
      - name: number-search-app
        image: joiltonsantos/number-search-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ELASTIC_APM_SERVER_URLS
          value: "http://apm-server:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "number-search-app"
        - name: ELASTIC_APM_ENVIRONMENT
          value: "development"
        stdin: true
        tty: true