apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: number-search
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: number-search
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    name: http
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: number-search
spec:
  selector:
    app: apm-server
  ports:
  - port: 8200
    name: http